# Site Info
title:              "Rivcod"
description:        "Flowing"
google_verify:       # Put your Google Verification here
google_analytics:   'G-L7BZ84ZHRE'
logo_url:           assets/cigg.png # Get it from GitHub API: https://api.github.com/users/<username>
theme: the-plain

# Author Info
author_name:        "Rivcod"
author_email:       game9um@gmail.com

github_username:    rivcod

# Site Settings
url:                https://rivcod.github.io
permalink:          /:title # Post permalink
timezone:           Asia/Seoul
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
